// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_model_status.proto

package tensorflow.serving;

public final class GetModelStatus {
  private GetModelStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetModelStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.GetModelStatusRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Model Specification. If version is not specified, information about all
     * versions of the model will be returned. If a version is specified, the
     * status of only that version will be returned.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    boolean hasModelSpec();
    /**
     * <pre>
     * Model Specification. If version is not specified, information about all
     * versions of the model will be returned. If a version is specified, the
     * status of only that version will be returned.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    Model.ModelSpec getModelSpec();
    /**
     * <pre>
     * Model Specification. If version is not specified, information about all
     * versions of the model will be returned. If a version is specified, the
     * status of only that version will be returned.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    Model.ModelSpecOrBuilder getModelSpecOrBuilder();
  }
  /**
   * <pre>
   * GetModelStatusRequest contains a ModelSpec indicating the model for which
   * to get status.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.GetModelStatusRequest}
   */
  public  static final class GetModelStatusRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.GetModelStatusRequest)
      GetModelStatusRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetModelStatusRequest.newBuilder() to construct.
    private GetModelStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetModelStatusRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetModelStatusRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetModelStatusRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Model.ModelSpec.Builder subBuilder = null;
              if (modelSpec_ != null) {
                subBuilder = modelSpec_.toBuilder();
              }
              modelSpec_ = input.readMessage(Model.ModelSpec.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(modelSpec_);
                modelSpec_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetModelStatus.GetModelStatusRequest.class, GetModelStatus.GetModelStatusRequest.Builder.class);
    }

    public static final int MODEL_SPEC_FIELD_NUMBER = 1;
    private Model.ModelSpec modelSpec_;
    /**
     * <pre>
     * Model Specification. If version is not specified, information about all
     * versions of the model will be returned. If a version is specified, the
     * status of only that version will be returned.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    public boolean hasModelSpec() {
      return modelSpec_ != null;
    }
    /**
     * <pre>
     * Model Specification. If version is not specified, information about all
     * versions of the model will be returned. If a version is specified, the
     * status of only that version will be returned.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    public Model.ModelSpec getModelSpec() {
      return modelSpec_ == null ? Model.ModelSpec.getDefaultInstance() : modelSpec_;
    }
    /**
     * <pre>
     * Model Specification. If version is not specified, information about all
     * versions of the model will be returned. If a version is specified, the
     * status of only that version will be returned.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    public Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
      return getModelSpec();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (modelSpec_ != null) {
        output.writeMessage(1, getModelSpec());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (modelSpec_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getModelSpec());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetModelStatus.GetModelStatusRequest)) {
        return super.equals(obj);
      }
      GetModelStatus.GetModelStatusRequest other = (GetModelStatus.GetModelStatusRequest) obj;

      if (hasModelSpec() != other.hasModelSpec()) return false;
      if (hasModelSpec()) {
        if (!getModelSpec()
            .equals(other.getModelSpec())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModelSpec()) {
        hash = (37 * hash) + MODEL_SPEC_FIELD_NUMBER;
        hash = (53 * hash) + getModelSpec().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetModelStatus.GetModelStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetModelStatus.GetModelStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetModelStatus.GetModelStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetModelStatus.GetModelStatusRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * GetModelStatusRequest contains a ModelSpec indicating the model for which
     * to get status.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.GetModelStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.GetModelStatusRequest)
        GetModelStatus.GetModelStatusRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetModelStatus.GetModelStatusRequest.class, GetModelStatus.GetModelStatusRequest.Builder.class);
      }

      // Construct using tensorflow.serving.GetModelStatus.GetModelStatusRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusRequest_descriptor;
      }

      @Override
      public GetModelStatus.GetModelStatusRequest getDefaultInstanceForType() {
        return GetModelStatus.GetModelStatusRequest.getDefaultInstance();
      }

      @Override
      public GetModelStatus.GetModelStatusRequest build() {
        GetModelStatus.GetModelStatusRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GetModelStatus.GetModelStatusRequest buildPartial() {
        GetModelStatus.GetModelStatusRequest result = new GetModelStatus.GetModelStatusRequest(this);
        if (modelSpecBuilder_ == null) {
          result.modelSpec_ = modelSpec_;
        } else {
          result.modelSpec_ = modelSpecBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetModelStatus.GetModelStatusRequest) {
          return mergeFrom((GetModelStatus.GetModelStatusRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetModelStatus.GetModelStatusRequest other) {
        if (other == GetModelStatus.GetModelStatusRequest.getDefaultInstance()) return this;
        if (other.hasModelSpec()) {
          mergeModelSpec(other.getModelSpec());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetModelStatus.GetModelStatusRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetModelStatus.GetModelStatusRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Model.ModelSpec modelSpec_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder> modelSpecBuilder_;
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public boolean hasModelSpec() {
        return modelSpecBuilder_ != null || modelSpec_ != null;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Model.ModelSpec getModelSpec() {
        if (modelSpecBuilder_ == null) {
          return modelSpec_ == null ? Model.ModelSpec.getDefaultInstance() : modelSpec_;
        } else {
          return modelSpecBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modelSpec_ = value;
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(
          Model.ModelSpec.Builder builderForValue) {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = builderForValue.build();
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder mergeModelSpec(Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (modelSpec_ != null) {
            modelSpec_ =
              Model.ModelSpec.newBuilder(modelSpec_).mergeFrom(value).buildPartial();
          } else {
            modelSpec_ = value;
          }
          onChanged();
        } else {
          modelSpecBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder clearModelSpec() {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
          onChanged();
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Model.ModelSpec.Builder getModelSpecBuilder() {

        onChanged();
        return getModelSpecFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
        if (modelSpecBuilder_ != null) {
          return modelSpecBuilder_.getMessageOrBuilder();
        } else {
          return modelSpec_ == null ?
              Model.ModelSpec.getDefaultInstance() : modelSpec_;
        }
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, information about all
       * versions of the model will be returned. If a version is specified, the
       * status of only that version will be returned.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder>
          getModelSpecFieldBuilder() {
        if (modelSpecBuilder_ == null) {
          modelSpecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder>(
                  getModelSpec(),
                  getParentForChildren(),
                  isClean());
          modelSpec_ = null;
        }
        return modelSpecBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.GetModelStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.GetModelStatusRequest)
    private static final GetModelStatus.GetModelStatusRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetModelStatus.GetModelStatusRequest();
    }

    public static GetModelStatus.GetModelStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetModelStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetModelStatusRequest>() {
      @Override
      public GetModelStatusRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetModelStatusRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetModelStatusRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetModelStatusRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public GetModelStatus.GetModelStatusRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ModelVersionStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.ModelVersionStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Model version.
     * </pre>
     *
     * <code>int64 version = 1;</code>
     */
    long getVersion();

    /**
     * <pre>
     * Model state.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
     */
    int getStateValue();
    /**
     * <pre>
     * Model state.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
     */
    GetModelStatus.ModelVersionStatus.State getState();

    /**
     * <pre>
     * Model status.
     * </pre>
     *
     * <code>.tensorflow.serving.StatusProto status = 3;</code>
     */
    boolean hasStatus();
    /**
     * <pre>
     * Model status.
     * </pre>
     *
     * <code>.tensorflow.serving.StatusProto status = 3;</code>
     */
    Status.StatusProto getStatus();
    /**
     * <pre>
     * Model status.
     * </pre>
     *
     * <code>.tensorflow.serving.StatusProto status = 3;</code>
     */
    Status.StatusProtoOrBuilder getStatusOrBuilder();
  }
  /**
   * <pre>
   * Version number, state, and status for a single version of a model.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.ModelVersionStatus}
   */
  public  static final class ModelVersionStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.ModelVersionStatus)
      ModelVersionStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ModelVersionStatus.newBuilder() to construct.
    private ModelVersionStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ModelVersionStatus() {
      state_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ModelVersionStatus();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ModelVersionStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 26: {
              Status.StatusProto.Builder subBuilder = null;
              if (status_ != null) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(Status.StatusProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetModelStatus.internal_static_tensorflow_serving_ModelVersionStatus_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetModelStatus.internal_static_tensorflow_serving_ModelVersionStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetModelStatus.ModelVersionStatus.class, GetModelStatus.ModelVersionStatus.Builder.class);
    }

    /**
     * <pre>
     * States that map to ManagerState enum in
     * tensorflow_serving/core/servable_state.h
     * </pre>
     *
     * Protobuf enum {@code tensorflow.serving.ModelVersionStatus.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Default value.
       * </pre>
       *
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <pre>
       * The manager is tracking this servable, but has not initiated any action
       * pertaining to it.
       * </pre>
       *
       * <code>START = 10;</code>
       */
      START(10),
      /**
       * <pre>
       * The manager has decided to load this servable. In particular, checks
       * around resource availability and other aspects have passed, and the
       * manager is about to invoke the loader's Load() method.
       * </pre>
       *
       * <code>LOADING = 20;</code>
       */
      LOADING(20),
      /**
       * <pre>
       * The manager has successfully loaded this servable and made it available
       * for serving (i.e. GetServableHandle(id) will succeed). To avoid races,
       * this state is not reported until *after* the servable is made
       * available.
       * </pre>
       *
       * <code>AVAILABLE = 30;</code>
       */
      AVAILABLE(30),
      /**
       * <pre>
       * The manager has decided to make this servable unavailable, and unload
       * it. To avoid races, this state is reported *before* the servable is
       * made unavailable.
       * </pre>
       *
       * <code>UNLOADING = 40;</code>
       */
      UNLOADING(40),
      /**
       * <pre>
       * This servable has reached the end of its journey in the manager. Either
       * it loaded and ultimately unloaded successfully, or it hit an error at
       * some point in its lifecycle.
       * </pre>
       *
       * <code>END = 50;</code>
       */
      END(50),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * Default value.
       * </pre>
       *
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <pre>
       * The manager is tracking this servable, but has not initiated any action
       * pertaining to it.
       * </pre>
       *
       * <code>START = 10;</code>
       */
      public static final int START_VALUE = 10;
      /**
       * <pre>
       * The manager has decided to load this servable. In particular, checks
       * around resource availability and other aspects have passed, and the
       * manager is about to invoke the loader's Load() method.
       * </pre>
       *
       * <code>LOADING = 20;</code>
       */
      public static final int LOADING_VALUE = 20;
      /**
       * <pre>
       * The manager has successfully loaded this servable and made it available
       * for serving (i.e. GetServableHandle(id) will succeed). To avoid races,
       * this state is not reported until *after* the servable is made
       * available.
       * </pre>
       *
       * <code>AVAILABLE = 30;</code>
       */
      public static final int AVAILABLE_VALUE = 30;
      /**
       * <pre>
       * The manager has decided to make this servable unavailable, and unload
       * it. To avoid races, this state is reported *before* the servable is
       * made unavailable.
       * </pre>
       *
       * <code>UNLOADING = 40;</code>
       */
      public static final int UNLOADING_VALUE = 40;
      /**
       * <pre>
       * This servable has reached the end of its journey in the manager. Either
       * it loaded and ultimately unloaded successfully, or it hit an error at
       * some point in its lifecycle.
       * </pre>
       *
       * <code>END = 50;</code>
       */
      public static final int END_VALUE = 50;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static State valueOf(int value) {
        return forNumber(value);
      }

      public static State forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 10: return START;
          case 20: return LOADING;
          case 30: return AVAILABLE;
          case 40: return UNLOADING;
          case 50: return END;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          State> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return GetModelStatus.ModelVersionStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private State(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tensorflow.serving.ModelVersionStatus.State)
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <pre>
     * Model version.
     * </pre>
     *
     * <code>int64 version = 1;</code>
     */
    public long getVersion() {
      return version_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <pre>
     * Model state.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * Model state.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
     */
    public GetModelStatus.ModelVersionStatus.State getState() {
      @SuppressWarnings("deprecation")
      GetModelStatus.ModelVersionStatus.State result = GetModelStatus.ModelVersionStatus.State.valueOf(state_);
      return result == null ? GetModelStatus.ModelVersionStatus.State.UNRECOGNIZED : result;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private Status.StatusProto status_;
    /**
     * <pre>
     * Model status.
     * </pre>
     *
     * <code>.tensorflow.serving.StatusProto status = 3;</code>
     */
    public boolean hasStatus() {
      return status_ != null;
    }
    /**
     * <pre>
     * Model status.
     * </pre>
     *
     * <code>.tensorflow.serving.StatusProto status = 3;</code>
     */
    public Status.StatusProto getStatus() {
      return status_ == null ? Status.StatusProto.getDefaultInstance() : status_;
    }
    /**
     * <pre>
     * Model status.
     * </pre>
     *
     * <code>.tensorflow.serving.StatusProto status = 3;</code>
     */
    public Status.StatusProtoOrBuilder getStatusOrBuilder() {
      return getStatus();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0L) {
        output.writeInt64(1, version_);
      }
      if (state_ != GetModelStatus.ModelVersionStatus.State.UNKNOWN.getNumber()) {
        output.writeEnum(2, state_);
      }
      if (status_ != null) {
        output.writeMessage(3, getStatus());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, version_);
      }
      if (state_ != GetModelStatus.ModelVersionStatus.State.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_);
      }
      if (status_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStatus());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetModelStatus.ModelVersionStatus)) {
        return super.equals(obj);
      }
      GetModelStatus.ModelVersionStatus other = (GetModelStatus.ModelVersionStatus) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (state_ != other.state_) return false;
      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (!getStatus()
            .equals(other.getStatus())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetModelStatus.ModelVersionStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetModelStatus.ModelVersionStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetModelStatus.ModelVersionStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetModelStatus.ModelVersionStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetModelStatus.ModelVersionStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Version number, state, and status for a single version of a model.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.ModelVersionStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.ModelVersionStatus)
        GetModelStatus.ModelVersionStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetModelStatus.internal_static_tensorflow_serving_ModelVersionStatus_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetModelStatus.internal_static_tensorflow_serving_ModelVersionStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetModelStatus.ModelVersionStatus.class, GetModelStatus.ModelVersionStatus.Builder.class);
      }

      // Construct using tensorflow.serving.GetModelStatus.ModelVersionStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        version_ = 0L;

        state_ = 0;

        if (statusBuilder_ == null) {
          status_ = null;
        } else {
          status_ = null;
          statusBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetModelStatus.internal_static_tensorflow_serving_ModelVersionStatus_descriptor;
      }

      @Override
      public GetModelStatus.ModelVersionStatus getDefaultInstanceForType() {
        return GetModelStatus.ModelVersionStatus.getDefaultInstance();
      }

      @Override
      public GetModelStatus.ModelVersionStatus build() {
        GetModelStatus.ModelVersionStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GetModelStatus.ModelVersionStatus buildPartial() {
        GetModelStatus.ModelVersionStatus result = new GetModelStatus.ModelVersionStatus(this);
        result.version_ = version_;
        result.state_ = state_;
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetModelStatus.ModelVersionStatus) {
          return mergeFrom((GetModelStatus.ModelVersionStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetModelStatus.ModelVersionStatus other) {
        if (other == GetModelStatus.ModelVersionStatus.getDefaultInstance()) return this;
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetModelStatus.ModelVersionStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetModelStatus.ModelVersionStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long version_ ;
      /**
       * <pre>
       * Model version.
       * </pre>
       *
       * <code>int64 version = 1;</code>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <pre>
       * Model version.
       * </pre>
       *
       * <code>int64 version = 1;</code>
       */
      public Builder setVersion(long value) {

        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Model version.
       * </pre>
       *
       * <code>int64 version = 1;</code>
       */
      public Builder clearVersion() {

        version_ = 0L;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <pre>
       * Model state.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <pre>
       * Model state.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Model state.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
       */
      public GetModelStatus.ModelVersionStatus.State getState() {
        @SuppressWarnings("deprecation")
        GetModelStatus.ModelVersionStatus.State result = GetModelStatus.ModelVersionStatus.State.valueOf(state_);
        return result == null ? GetModelStatus.ModelVersionStatus.State.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Model state.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
       */
      public Builder setState(GetModelStatus.ModelVersionStatus.State value) {
        if (value == null) {
          throw new NullPointerException();
        }

        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Model state.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelVersionStatus.State state = 2;</code>
       */
      public Builder clearState() {

        state_ = 0;
        onChanged();
        return this;
      }

      private Status.StatusProto status_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Status.StatusProto, Status.StatusProto.Builder, Status.StatusProtoOrBuilder> statusBuilder_;
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      public boolean hasStatus() {
        return statusBuilder_ != null || status_ != null;
      }
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      public Status.StatusProto getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? Status.StatusProto.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      public Builder setStatus(Status.StatusProto value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      public Builder setStatus(
          Status.StatusProto.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      public Builder mergeStatus(Status.StatusProto value) {
        if (statusBuilder_ == null) {
          if (status_ != null) {
            status_ =
              Status.StatusProto.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = null;
          onChanged();
        } else {
          status_ = null;
          statusBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      public Status.StatusProto.Builder getStatusBuilder() {

        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      public Status.StatusProtoOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              Status.StatusProto.getDefaultInstance() : status_;
        }
      }
      /**
       * <pre>
       * Model status.
       * </pre>
       *
       * <code>.tensorflow.serving.StatusProto status = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Status.StatusProto, Status.StatusProto.Builder, Status.StatusProtoOrBuilder>
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Status.StatusProto, Status.StatusProto.Builder, Status.StatusProtoOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.ModelVersionStatus)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.ModelVersionStatus)
    private static final GetModelStatus.ModelVersionStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetModelStatus.ModelVersionStatus();
    }

    public static GetModelStatus.ModelVersionStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ModelVersionStatus>
        PARSER = new com.google.protobuf.AbstractParser<ModelVersionStatus>() {
      @Override
      public ModelVersionStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModelVersionStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ModelVersionStatus> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ModelVersionStatus> getParserForType() {
      return PARSER;
    }

    @Override
    public GetModelStatus.ModelVersionStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetModelStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.GetModelStatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    java.util.List<ModelVersionStatus>
        getModelVersionStatusList();
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    GetModelStatus.ModelVersionStatus getModelVersionStatus(int index);
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    int getModelVersionStatusCount();
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    java.util.List<? extends ModelVersionStatusOrBuilder>
        getModelVersionStatusOrBuilderList();
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    GetModelStatus.ModelVersionStatusOrBuilder getModelVersionStatusOrBuilder(
            int index);
  }
  /**
   * <pre>
   * Response for ModelStatusRequest on successful run.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.GetModelStatusResponse}
   */
  public  static final class GetModelStatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.GetModelStatusResponse)
      GetModelStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetModelStatusResponse.newBuilder() to construct.
    private GetModelStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetModelStatusResponse() {
      modelVersionStatus_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetModelStatusResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetModelStatusResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                modelVersionStatus_ = new java.util.ArrayList<ModelVersionStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              modelVersionStatus_.add(
                  input.readMessage(GetModelStatus.ModelVersionStatus.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          modelVersionStatus_ = java.util.Collections.unmodifiableList(modelVersionStatus_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetModelStatus.GetModelStatusResponse.class, GetModelStatus.GetModelStatusResponse.Builder.class);
    }

    public static final int MODEL_VERSION_STATUS_FIELD_NUMBER = 1;
    private java.util.List<ModelVersionStatus> modelVersionStatus_;
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    public java.util.List<ModelVersionStatus> getModelVersionStatusList() {
      return modelVersionStatus_;
    }
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    public java.util.List<? extends ModelVersionStatusOrBuilder>
        getModelVersionStatusOrBuilderList() {
      return modelVersionStatus_;
    }
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    public int getModelVersionStatusCount() {
      return modelVersionStatus_.size();
    }
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    public GetModelStatus.ModelVersionStatus getModelVersionStatus(int index) {
      return modelVersionStatus_.get(index);
    }
    /**
     * <pre>
     * Version number and status information for applicable model version(s).
     * </pre>
     *
     * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
     */
    public GetModelStatus.ModelVersionStatusOrBuilder getModelVersionStatusOrBuilder(
        int index) {
      return modelVersionStatus_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < modelVersionStatus_.size(); i++) {
        output.writeMessage(1, modelVersionStatus_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < modelVersionStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, modelVersionStatus_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetModelStatus.GetModelStatusResponse)) {
        return super.equals(obj);
      }
      GetModelStatus.GetModelStatusResponse other = (GetModelStatus.GetModelStatusResponse) obj;

      if (!getModelVersionStatusList()
          .equals(other.getModelVersionStatusList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getModelVersionStatusCount() > 0) {
        hash = (37 * hash) + MODEL_VERSION_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getModelVersionStatusList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetModelStatus.GetModelStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetModelStatus.GetModelStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetModelStatus.GetModelStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetModelStatus.GetModelStatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response for ModelStatusRequest on successful run.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.GetModelStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.GetModelStatusResponse)
        GetModelStatus.GetModelStatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetModelStatus.GetModelStatusResponse.class, GetModelStatus.GetModelStatusResponse.Builder.class);
      }

      // Construct using tensorflow.serving.GetModelStatus.GetModelStatusResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getModelVersionStatusFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (modelVersionStatusBuilder_ == null) {
          modelVersionStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          modelVersionStatusBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetModelStatus.internal_static_tensorflow_serving_GetModelStatusResponse_descriptor;
      }

      @Override
      public GetModelStatus.GetModelStatusResponse getDefaultInstanceForType() {
        return GetModelStatus.GetModelStatusResponse.getDefaultInstance();
      }

      @Override
      public GetModelStatus.GetModelStatusResponse build() {
        GetModelStatus.GetModelStatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GetModelStatus.GetModelStatusResponse buildPartial() {
        GetModelStatus.GetModelStatusResponse result = new GetModelStatus.GetModelStatusResponse(this);
        int from_bitField0_ = bitField0_;
        if (modelVersionStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            modelVersionStatus_ = java.util.Collections.unmodifiableList(modelVersionStatus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.modelVersionStatus_ = modelVersionStatus_;
        } else {
          result.modelVersionStatus_ = modelVersionStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetModelStatus.GetModelStatusResponse) {
          return mergeFrom((GetModelStatus.GetModelStatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetModelStatus.GetModelStatusResponse other) {
        if (other == GetModelStatus.GetModelStatusResponse.getDefaultInstance()) return this;
        if (modelVersionStatusBuilder_ == null) {
          if (!other.modelVersionStatus_.isEmpty()) {
            if (modelVersionStatus_.isEmpty()) {
              modelVersionStatus_ = other.modelVersionStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureModelVersionStatusIsMutable();
              modelVersionStatus_.addAll(other.modelVersionStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.modelVersionStatus_.isEmpty()) {
            if (modelVersionStatusBuilder_.isEmpty()) {
              modelVersionStatusBuilder_.dispose();
              modelVersionStatusBuilder_ = null;
              modelVersionStatus_ = other.modelVersionStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              modelVersionStatusBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getModelVersionStatusFieldBuilder() : null;
            } else {
              modelVersionStatusBuilder_.addAllMessages(other.modelVersionStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetModelStatus.GetModelStatusResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetModelStatus.GetModelStatusResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ModelVersionStatus> modelVersionStatus_ =
        java.util.Collections.emptyList();
      private void ensureModelVersionStatusIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          modelVersionStatus_ = new java.util.ArrayList<ModelVersionStatus>(modelVersionStatus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ModelVersionStatus, ModelVersionStatus.Builder, ModelVersionStatusOrBuilder> modelVersionStatusBuilder_;

      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public java.util.List<ModelVersionStatus> getModelVersionStatusList() {
        if (modelVersionStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(modelVersionStatus_);
        } else {
          return modelVersionStatusBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public int getModelVersionStatusCount() {
        if (modelVersionStatusBuilder_ == null) {
          return modelVersionStatus_.size();
        } else {
          return modelVersionStatusBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public GetModelStatus.ModelVersionStatus getModelVersionStatus(int index) {
        if (modelVersionStatusBuilder_ == null) {
          return modelVersionStatus_.get(index);
        } else {
          return modelVersionStatusBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder setModelVersionStatus(
          int index, GetModelStatus.ModelVersionStatus value) {
        if (modelVersionStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModelVersionStatusIsMutable();
          modelVersionStatus_.set(index, value);
          onChanged();
        } else {
          modelVersionStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder setModelVersionStatus(
          int index, GetModelStatus.ModelVersionStatus.Builder builderForValue) {
        if (modelVersionStatusBuilder_ == null) {
          ensureModelVersionStatusIsMutable();
          modelVersionStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          modelVersionStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder addModelVersionStatus(GetModelStatus.ModelVersionStatus value) {
        if (modelVersionStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModelVersionStatusIsMutable();
          modelVersionStatus_.add(value);
          onChanged();
        } else {
          modelVersionStatusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder addModelVersionStatus(
          int index, GetModelStatus.ModelVersionStatus value) {
        if (modelVersionStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModelVersionStatusIsMutable();
          modelVersionStatus_.add(index, value);
          onChanged();
        } else {
          modelVersionStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder addModelVersionStatus(
          GetModelStatus.ModelVersionStatus.Builder builderForValue) {
        if (modelVersionStatusBuilder_ == null) {
          ensureModelVersionStatusIsMutable();
          modelVersionStatus_.add(builderForValue.build());
          onChanged();
        } else {
          modelVersionStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder addModelVersionStatus(
          int index, GetModelStatus.ModelVersionStatus.Builder builderForValue) {
        if (modelVersionStatusBuilder_ == null) {
          ensureModelVersionStatusIsMutable();
          modelVersionStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          modelVersionStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder addAllModelVersionStatus(
          Iterable<? extends ModelVersionStatus> values) {
        if (modelVersionStatusBuilder_ == null) {
          ensureModelVersionStatusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, modelVersionStatus_);
          onChanged();
        } else {
          modelVersionStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder clearModelVersionStatus() {
        if (modelVersionStatusBuilder_ == null) {
          modelVersionStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          modelVersionStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public Builder removeModelVersionStatus(int index) {
        if (modelVersionStatusBuilder_ == null) {
          ensureModelVersionStatusIsMutable();
          modelVersionStatus_.remove(index);
          onChanged();
        } else {
          modelVersionStatusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public GetModelStatus.ModelVersionStatus.Builder getModelVersionStatusBuilder(
          int index) {
        return getModelVersionStatusFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public GetModelStatus.ModelVersionStatusOrBuilder getModelVersionStatusOrBuilder(
          int index) {
        if (modelVersionStatusBuilder_ == null) {
          return modelVersionStatus_.get(index);  } else {
          return modelVersionStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public java.util.List<? extends ModelVersionStatusOrBuilder>
           getModelVersionStatusOrBuilderList() {
        if (modelVersionStatusBuilder_ != null) {
          return modelVersionStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(modelVersionStatus_);
        }
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public GetModelStatus.ModelVersionStatus.Builder addModelVersionStatusBuilder() {
        return getModelVersionStatusFieldBuilder().addBuilder(
            GetModelStatus.ModelVersionStatus.getDefaultInstance());
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public GetModelStatus.ModelVersionStatus.Builder addModelVersionStatusBuilder(
          int index) {
        return getModelVersionStatusFieldBuilder().addBuilder(
            index, GetModelStatus.ModelVersionStatus.getDefaultInstance());
      }
      /**
       * <pre>
       * Version number and status information for applicable model version(s).
       * </pre>
       *
       * <code>repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1[json_name = "model_version_status"];</code>
       */
      public java.util.List<ModelVersionStatus.Builder>
           getModelVersionStatusBuilderList() {
        return getModelVersionStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ModelVersionStatus, ModelVersionStatus.Builder, ModelVersionStatusOrBuilder>
          getModelVersionStatusFieldBuilder() {
        if (modelVersionStatusBuilder_ == null) {
          modelVersionStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ModelVersionStatus, ModelVersionStatus.Builder, ModelVersionStatusOrBuilder>(
                  modelVersionStatus_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          modelVersionStatus_ = null;
        }
        return modelVersionStatusBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.GetModelStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.GetModelStatusResponse)
    private static final GetModelStatus.GetModelStatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetModelStatus.GetModelStatusResponse();
    }

    public static GetModelStatus.GetModelStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetModelStatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetModelStatusResponse>() {
      @Override
      public GetModelStatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetModelStatusResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetModelStatusResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetModelStatusResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public GetModelStatus.GetModelStatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_GetModelStatusRequest_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_GetModelStatusRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_ModelVersionStatus_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_ModelVersionStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_GetModelStatusResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_GetModelStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026get_model_status.proto\022\022tensorflow.ser" +
      "ving\032\013model.proto\032\014status.proto\"J\n\025GetMo" +
      "delStatusRequest\0221\n\nmodel_spec\030\001 \001(\0132\035.t" +
      "ensorflow.serving.ModelSpec\"\350\001\n\022ModelVer" +
      "sionStatus\022\017\n\007version\030\001 \001(\003\022;\n\005state\030\002 \001" +
      "(\0162,.tensorflow.serving.ModelVersionStat" +
      "us.State\022/\n\006status\030\003 \001(\0132\037.tensorflow.se" +
      "rving.StatusProto\"S\n\005State\022\013\n\007UNKNOWN\020\000\022" +
      "\t\n\005START\020\n\022\013\n\007LOADING\020\024\022\r\n\tAVAILABLE\020\036\022\r" +
      "\n\tUNLOADING\020(\022\007\n\003END\0202\"t\n\026GetModelStatus" +
      "Response\022Z\n\024model_version_status\030\001 \003(\0132&" +
      ".tensorflow.serving.ModelVersionStatusR\024" +
      "model_version_statusB\003\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Model.getDescriptor(),
          Status.getDescriptor(),
        });
    internal_static_tensorflow_serving_GetModelStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_GetModelStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_GetModelStatusRequest_descriptor,
        new String[] { "ModelSpec", });
    internal_static_tensorflow_serving_ModelVersionStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_serving_ModelVersionStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_ModelVersionStatus_descriptor,
        new String[] { "Version", "State", "Status", });
    internal_static_tensorflow_serving_GetModelStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_serving_GetModelStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_GetModelStatusResponse_descriptor,
        new String[] { "ModelVersionStatus", });
    Model.getDescriptor();
    Status.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
