// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_collector_config.proto

package tensorflow.serving;

public final class LogCollectorConfigOuterClass {
  private LogCollectorConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogCollectorConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.LogCollectorConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Identifies the type of the LogCollector we will use to collect these logs.
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    String getType();
    /**
     * <pre>
     * Identifies the type of the LogCollector we will use to collect these logs.
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * The prefix to use for the filenames of the logs.
     * </pre>
     *
     * <code>string filename_prefix = 2;</code>
     */
    String getFilenamePrefix();
    /**
     * <pre>
     * The prefix to use for the filenames of the logs.
     * </pre>
     *
     * <code>string filename_prefix = 2;</code>
     */
    com.google.protobuf.ByteString
        getFilenamePrefixBytes();
  }
  /**
   * Protobuf type {@code tensorflow.serving.LogCollectorConfig}
   */
  public  static final class LogCollectorConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.LogCollectorConfig)
      LogCollectorConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogCollectorConfig.newBuilder() to construct.
    private LogCollectorConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogCollectorConfig() {
      type_ = "";
      filenamePrefix_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogCollectorConfig();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogCollectorConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              filenamePrefix_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogCollectorConfigOuterClass.internal_static_tensorflow_serving_LogCollectorConfig_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogCollectorConfigOuterClass.internal_static_tensorflow_serving_LogCollectorConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogCollectorConfigOuterClass.LogCollectorConfig.class, LogCollectorConfigOuterClass.LogCollectorConfig.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile Object type_;
    /**
     * <pre>
     * Identifies the type of the LogCollector we will use to collect these logs.
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Identifies the type of the LogCollector we will use to collect these logs.
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILENAME_PREFIX_FIELD_NUMBER = 2;
    private volatile Object filenamePrefix_;
    /**
     * <pre>
     * The prefix to use for the filenames of the logs.
     * </pre>
     *
     * <code>string filename_prefix = 2;</code>
     */
    public String getFilenamePrefix() {
      Object ref = filenamePrefix_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        filenamePrefix_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The prefix to use for the filenames of the logs.
     * </pre>
     *
     * <code>string filename_prefix = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFilenamePrefixBytes() {
      Object ref = filenamePrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        filenamePrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!getFilenamePrefixBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filenamePrefix_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!getFilenamePrefixBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filenamePrefix_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LogCollectorConfigOuterClass.LogCollectorConfig)) {
        return super.equals(obj);
      }
      LogCollectorConfigOuterClass.LogCollectorConfig other = (LogCollectorConfigOuterClass.LogCollectorConfig) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getFilenamePrefix()
          .equals(other.getFilenamePrefix())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + FILENAME_PREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getFilenamePrefix().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogCollectorConfigOuterClass.LogCollectorConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LogCollectorConfigOuterClass.LogCollectorConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.serving.LogCollectorConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.LogCollectorConfig)
        LogCollectorConfigOuterClass.LogCollectorConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogCollectorConfigOuterClass.internal_static_tensorflow_serving_LogCollectorConfig_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogCollectorConfigOuterClass.internal_static_tensorflow_serving_LogCollectorConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LogCollectorConfigOuterClass.LogCollectorConfig.class, LogCollectorConfigOuterClass.LogCollectorConfig.Builder.class);
      }

      // Construct using tensorflow.serving.LogCollectorConfigOuterClass.LogCollectorConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = "";

        filenamePrefix_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LogCollectorConfigOuterClass.internal_static_tensorflow_serving_LogCollectorConfig_descriptor;
      }

      @Override
      public LogCollectorConfigOuterClass.LogCollectorConfig getDefaultInstanceForType() {
        return LogCollectorConfigOuterClass.LogCollectorConfig.getDefaultInstance();
      }

      @Override
      public LogCollectorConfigOuterClass.LogCollectorConfig build() {
        LogCollectorConfigOuterClass.LogCollectorConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LogCollectorConfigOuterClass.LogCollectorConfig buildPartial() {
        LogCollectorConfigOuterClass.LogCollectorConfig result = new LogCollectorConfigOuterClass.LogCollectorConfig(this);
        result.type_ = type_;
        result.filenamePrefix_ = filenamePrefix_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LogCollectorConfigOuterClass.LogCollectorConfig) {
          return mergeFrom((LogCollectorConfigOuterClass.LogCollectorConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LogCollectorConfigOuterClass.LogCollectorConfig other) {
        if (other == LogCollectorConfigOuterClass.LogCollectorConfig.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getFilenamePrefix().isEmpty()) {
          filenamePrefix_ = other.filenamePrefix_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LogCollectorConfigOuterClass.LogCollectorConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LogCollectorConfigOuterClass.LogCollectorConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object type_ = "";
      /**
       * <pre>
       * Identifies the type of the LogCollector we will use to collect these logs.
       * </pre>
       *
       * <code>string type = 1;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Identifies the type of the LogCollector we will use to collect these logs.
       * </pre>
       *
       * <code>string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Identifies the type of the LogCollector we will use to collect these logs.
       * </pre>
       *
       * <code>string type = 1;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Identifies the type of the LogCollector we will use to collect these logs.
       * </pre>
       *
       * <code>string type = 1;</code>
       */
      public Builder clearType() {

        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Identifies the type of the LogCollector we will use to collect these logs.
       * </pre>
       *
       * <code>string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        type_ = value;
        onChanged();
        return this;
      }

      private Object filenamePrefix_ = "";
      /**
       * <pre>
       * The prefix to use for the filenames of the logs.
       * </pre>
       *
       * <code>string filename_prefix = 2;</code>
       */
      public String getFilenamePrefix() {
        Object ref = filenamePrefix_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          filenamePrefix_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * The prefix to use for the filenames of the logs.
       * </pre>
       *
       * <code>string filename_prefix = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFilenamePrefixBytes() {
        Object ref = filenamePrefix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          filenamePrefix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The prefix to use for the filenames of the logs.
       * </pre>
       *
       * <code>string filename_prefix = 2;</code>
       */
      public Builder setFilenamePrefix(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        filenamePrefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The prefix to use for the filenames of the logs.
       * </pre>
       *
       * <code>string filename_prefix = 2;</code>
       */
      public Builder clearFilenamePrefix() {

        filenamePrefix_ = getDefaultInstance().getFilenamePrefix();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The prefix to use for the filenames of the logs.
       * </pre>
       *
       * <code>string filename_prefix = 2;</code>
       */
      public Builder setFilenamePrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        filenamePrefix_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.LogCollectorConfig)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.LogCollectorConfig)
    private static final LogCollectorConfigOuterClass.LogCollectorConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogCollectorConfigOuterClass.LogCollectorConfig();
    }

    public static LogCollectorConfigOuterClass.LogCollectorConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogCollectorConfig>
        PARSER = new com.google.protobuf.AbstractParser<LogCollectorConfig>() {
      @Override
      public LogCollectorConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogCollectorConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogCollectorConfig> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LogCollectorConfig> getParserForType() {
      return PARSER;
    }

    @Override
    public LogCollectorConfigOuterClass.LogCollectorConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_LogCollectorConfig_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_LogCollectorConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032log_collector_config.proto\022\022tensorflow" +
      ".serving\";\n\022LogCollectorConfig\022\014\n\004type\030\001" +
      " \001(\t\022\027\n\017filename_prefix\030\002 \001(\tB\003\370\001\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tensorflow_serving_LogCollectorConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_LogCollectorConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_LogCollectorConfig_descriptor,
        new String[] { "Type", "FilenamePrefix", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
