// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logging_config.proto

package tensorflow.serving;

public final class LoggingConfigOuterClass {
  private LoggingConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SamplingConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.SamplingConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Requests will be logged uniformly at random with this probability. Valid
     * range: [0, 1.0].
     * </pre>
     *
     * <code>double sampling_rate = 1;</code>
     */
    double getSamplingRate();
  }
  /**
   * Protobuf type {@code tensorflow.serving.SamplingConfig}
   */
  public  static final class SamplingConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.SamplingConfig)
      SamplingConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SamplingConfig.newBuilder() to construct.
    private SamplingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SamplingConfig() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SamplingConfig();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SamplingConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              samplingRate_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoggingConfigOuterClass.internal_static_tensorflow_serving_SamplingConfig_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoggingConfigOuterClass.internal_static_tensorflow_serving_SamplingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoggingConfigOuterClass.SamplingConfig.class, LoggingConfigOuterClass.SamplingConfig.Builder.class);
    }

    public static final int SAMPLING_RATE_FIELD_NUMBER = 1;
    private double samplingRate_;
    /**
     * <pre>
     * Requests will be logged uniformly at random with this probability. Valid
     * range: [0, 1.0].
     * </pre>
     *
     * <code>double sampling_rate = 1;</code>
     */
    public double getSamplingRate() {
      return samplingRate_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (samplingRate_ != 0D) {
        output.writeDouble(1, samplingRate_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (samplingRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, samplingRate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoggingConfigOuterClass.SamplingConfig)) {
        return super.equals(obj);
      }
      LoggingConfigOuterClass.SamplingConfig other = (LoggingConfigOuterClass.SamplingConfig) obj;

      if (Double.doubleToLongBits(getSamplingRate())
          != Double.doubleToLongBits(
              other.getSamplingRate())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SAMPLING_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getSamplingRate()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoggingConfigOuterClass.SamplingConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoggingConfigOuterClass.SamplingConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoggingConfigOuterClass.SamplingConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.serving.SamplingConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.SamplingConfig)
        LoggingConfigOuterClass.SamplingConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoggingConfigOuterClass.internal_static_tensorflow_serving_SamplingConfig_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoggingConfigOuterClass.internal_static_tensorflow_serving_SamplingConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoggingConfigOuterClass.SamplingConfig.class, LoggingConfigOuterClass.SamplingConfig.Builder.class);
      }

      // Construct using tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        samplingRate_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoggingConfigOuterClass.internal_static_tensorflow_serving_SamplingConfig_descriptor;
      }

      @Override
      public LoggingConfigOuterClass.SamplingConfig getDefaultInstanceForType() {
        return LoggingConfigOuterClass.SamplingConfig.getDefaultInstance();
      }

      @Override
      public LoggingConfigOuterClass.SamplingConfig build() {
        LoggingConfigOuterClass.SamplingConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LoggingConfigOuterClass.SamplingConfig buildPartial() {
        LoggingConfigOuterClass.SamplingConfig result = new LoggingConfigOuterClass.SamplingConfig(this);
        result.samplingRate_ = samplingRate_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoggingConfigOuterClass.SamplingConfig) {
          return mergeFrom((LoggingConfigOuterClass.SamplingConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoggingConfigOuterClass.SamplingConfig other) {
        if (other == LoggingConfigOuterClass.SamplingConfig.getDefaultInstance()) return this;
        if (other.getSamplingRate() != 0D) {
          setSamplingRate(other.getSamplingRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoggingConfigOuterClass.SamplingConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoggingConfigOuterClass.SamplingConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double samplingRate_ ;
      /**
       * <pre>
       * Requests will be logged uniformly at random with this probability. Valid
       * range: [0, 1.0].
       * </pre>
       *
       * <code>double sampling_rate = 1;</code>
       */
      public double getSamplingRate() {
        return samplingRate_;
      }
      /**
       * <pre>
       * Requests will be logged uniformly at random with this probability. Valid
       * range: [0, 1.0].
       * </pre>
       *
       * <code>double sampling_rate = 1;</code>
       */
      public Builder setSamplingRate(double value) {

        samplingRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Requests will be logged uniformly at random with this probability. Valid
       * range: [0, 1.0].
       * </pre>
       *
       * <code>double sampling_rate = 1;</code>
       */
      public Builder clearSamplingRate() {

        samplingRate_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.SamplingConfig)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.SamplingConfig)
    private static final LoggingConfigOuterClass.SamplingConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoggingConfigOuterClass.SamplingConfig();
    }

    public static LoggingConfigOuterClass.SamplingConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SamplingConfig>
        PARSER = new com.google.protobuf.AbstractParser<SamplingConfig>() {
      @Override
      public SamplingConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SamplingConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SamplingConfig> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SamplingConfig> getParserForType() {
      return PARSER;
    }

    @Override
    public LoggingConfigOuterClass.SamplingConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoggingConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.LoggingConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
     */
    boolean hasLogCollectorConfig();
    /**
     * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
     */
    LogCollectorConfigOuterClass.LogCollectorConfig getLogCollectorConfig();
    /**
     * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
     */
    LogCollectorConfigOuterClass.LogCollectorConfigOrBuilder getLogCollectorConfigOrBuilder();

    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    boolean hasSamplingConfig();
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    LoggingConfigOuterClass.SamplingConfig getSamplingConfig();
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder();
  }
  /**
   * <pre>
   * Configuration for logging query/responses.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.LoggingConfig}
   */
  public  static final class LoggingConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.LoggingConfig)
      LoggingConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoggingConfig.newBuilder() to construct.
    private LoggingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoggingConfig() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoggingConfig();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoggingConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              LogCollectorConfigOuterClass.LogCollectorConfig.Builder subBuilder = null;
              if (logCollectorConfig_ != null) {
                subBuilder = logCollectorConfig_.toBuilder();
              }
              logCollectorConfig_ = input.readMessage(LogCollectorConfigOuterClass.LogCollectorConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(logCollectorConfig_);
                logCollectorConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              LoggingConfigOuterClass.SamplingConfig.Builder subBuilder = null;
              if (samplingConfig_ != null) {
                subBuilder = samplingConfig_.toBuilder();
              }
              samplingConfig_ = input.readMessage(LoggingConfigOuterClass.SamplingConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(samplingConfig_);
                samplingConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoggingConfigOuterClass.internal_static_tensorflow_serving_LoggingConfig_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoggingConfigOuterClass.internal_static_tensorflow_serving_LoggingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoggingConfigOuterClass.LoggingConfig.class, LoggingConfigOuterClass.LoggingConfig.Builder.class);
    }

    public static final int LOG_COLLECTOR_CONFIG_FIELD_NUMBER = 1;
    private LogCollectorConfigOuterClass.LogCollectorConfig logCollectorConfig_;
    /**
     * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
     */
    public boolean hasLogCollectorConfig() {
      return logCollectorConfig_ != null;
    }
    /**
     * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
     */
    public LogCollectorConfigOuterClass.LogCollectorConfig getLogCollectorConfig() {
      return logCollectorConfig_ == null ? LogCollectorConfigOuterClass.LogCollectorConfig.getDefaultInstance() : logCollectorConfig_;
    }
    /**
     * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
     */
    public LogCollectorConfigOuterClass.LogCollectorConfigOrBuilder getLogCollectorConfigOrBuilder() {
      return getLogCollectorConfig();
    }

    public static final int SAMPLING_CONFIG_FIELD_NUMBER = 2;
    private LoggingConfigOuterClass.SamplingConfig samplingConfig_;
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    public boolean hasSamplingConfig() {
      return samplingConfig_ != null;
    }
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    public LoggingConfigOuterClass.SamplingConfig getSamplingConfig() {
      return samplingConfig_ == null ? LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
    }
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    public LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
      return getSamplingConfig();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (logCollectorConfig_ != null) {
        output.writeMessage(1, getLogCollectorConfig());
      }
      if (samplingConfig_ != null) {
        output.writeMessage(2, getSamplingConfig());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (logCollectorConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLogCollectorConfig());
      }
      if (samplingConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSamplingConfig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoggingConfigOuterClass.LoggingConfig)) {
        return super.equals(obj);
      }
      LoggingConfigOuterClass.LoggingConfig other = (LoggingConfigOuterClass.LoggingConfig) obj;

      if (hasLogCollectorConfig() != other.hasLogCollectorConfig()) return false;
      if (hasLogCollectorConfig()) {
        if (!getLogCollectorConfig()
            .equals(other.getLogCollectorConfig())) return false;
      }
      if (hasSamplingConfig() != other.hasSamplingConfig()) return false;
      if (hasSamplingConfig()) {
        if (!getSamplingConfig()
            .equals(other.getSamplingConfig())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLogCollectorConfig()) {
        hash = (37 * hash) + LOG_COLLECTOR_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getLogCollectorConfig().hashCode();
      }
      if (hasSamplingConfig()) {
        hash = (37 * hash) + SAMPLING_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getSamplingConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoggingConfigOuterClass.LoggingConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoggingConfigOuterClass.LoggingConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoggingConfigOuterClass.LoggingConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration for logging query/responses.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.LoggingConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.LoggingConfig)
        LoggingConfigOuterClass.LoggingConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoggingConfigOuterClass.internal_static_tensorflow_serving_LoggingConfig_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoggingConfigOuterClass.internal_static_tensorflow_serving_LoggingConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoggingConfigOuterClass.LoggingConfig.class, LoggingConfigOuterClass.LoggingConfig.Builder.class);
      }

      // Construct using tensorflow.serving.LoggingConfigOuterClass.LoggingConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (logCollectorConfigBuilder_ == null) {
          logCollectorConfig_ = null;
        } else {
          logCollectorConfig_ = null;
          logCollectorConfigBuilder_ = null;
        }
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = null;
        } else {
          samplingConfig_ = null;
          samplingConfigBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoggingConfigOuterClass.internal_static_tensorflow_serving_LoggingConfig_descriptor;
      }

      @Override
      public LoggingConfigOuterClass.LoggingConfig getDefaultInstanceForType() {
        return LoggingConfigOuterClass.LoggingConfig.getDefaultInstance();
      }

      @Override
      public LoggingConfigOuterClass.LoggingConfig build() {
        LoggingConfigOuterClass.LoggingConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LoggingConfigOuterClass.LoggingConfig buildPartial() {
        LoggingConfigOuterClass.LoggingConfig result = new LoggingConfigOuterClass.LoggingConfig(this);
        if (logCollectorConfigBuilder_ == null) {
          result.logCollectorConfig_ = logCollectorConfig_;
        } else {
          result.logCollectorConfig_ = logCollectorConfigBuilder_.build();
        }
        if (samplingConfigBuilder_ == null) {
          result.samplingConfig_ = samplingConfig_;
        } else {
          result.samplingConfig_ = samplingConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoggingConfigOuterClass.LoggingConfig) {
          return mergeFrom((LoggingConfigOuterClass.LoggingConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoggingConfigOuterClass.LoggingConfig other) {
        if (other == LoggingConfigOuterClass.LoggingConfig.getDefaultInstance()) return this;
        if (other.hasLogCollectorConfig()) {
          mergeLogCollectorConfig(other.getLogCollectorConfig());
        }
        if (other.hasSamplingConfig()) {
          mergeSamplingConfig(other.getSamplingConfig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoggingConfigOuterClass.LoggingConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoggingConfigOuterClass.LoggingConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private LogCollectorConfigOuterClass.LogCollectorConfig logCollectorConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          LogCollectorConfigOuterClass.LogCollectorConfig, LogCollectorConfigOuterClass.LogCollectorConfig.Builder, LogCollectorConfigOuterClass.LogCollectorConfigOrBuilder> logCollectorConfigBuilder_;
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      public boolean hasLogCollectorConfig() {
        return logCollectorConfigBuilder_ != null || logCollectorConfig_ != null;
      }
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      public LogCollectorConfigOuterClass.LogCollectorConfig getLogCollectorConfig() {
        if (logCollectorConfigBuilder_ == null) {
          return logCollectorConfig_ == null ? LogCollectorConfigOuterClass.LogCollectorConfig.getDefaultInstance() : logCollectorConfig_;
        } else {
          return logCollectorConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      public Builder setLogCollectorConfig(LogCollectorConfigOuterClass.LogCollectorConfig value) {
        if (logCollectorConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logCollectorConfig_ = value;
          onChanged();
        } else {
          logCollectorConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      public Builder setLogCollectorConfig(
          LogCollectorConfigOuterClass.LogCollectorConfig.Builder builderForValue) {
        if (logCollectorConfigBuilder_ == null) {
          logCollectorConfig_ = builderForValue.build();
          onChanged();
        } else {
          logCollectorConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      public Builder mergeLogCollectorConfig(LogCollectorConfigOuterClass.LogCollectorConfig value) {
        if (logCollectorConfigBuilder_ == null) {
          if (logCollectorConfig_ != null) {
            logCollectorConfig_ =
              LogCollectorConfigOuterClass.LogCollectorConfig.newBuilder(logCollectorConfig_).mergeFrom(value).buildPartial();
          } else {
            logCollectorConfig_ = value;
          }
          onChanged();
        } else {
          logCollectorConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      public Builder clearLogCollectorConfig() {
        if (logCollectorConfigBuilder_ == null) {
          logCollectorConfig_ = null;
          onChanged();
        } else {
          logCollectorConfig_ = null;
          logCollectorConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      public LogCollectorConfigOuterClass.LogCollectorConfig.Builder getLogCollectorConfigBuilder() {

        onChanged();
        return getLogCollectorConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      public LogCollectorConfigOuterClass.LogCollectorConfigOrBuilder getLogCollectorConfigOrBuilder() {
        if (logCollectorConfigBuilder_ != null) {
          return logCollectorConfigBuilder_.getMessageOrBuilder();
        } else {
          return logCollectorConfig_ == null ?
              LogCollectorConfigOuterClass.LogCollectorConfig.getDefaultInstance() : logCollectorConfig_;
        }
      }
      /**
       * <code>.tensorflow.serving.LogCollectorConfig log_collector_config = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          LogCollectorConfigOuterClass.LogCollectorConfig, LogCollectorConfigOuterClass.LogCollectorConfig.Builder, LogCollectorConfigOuterClass.LogCollectorConfigOrBuilder>
          getLogCollectorConfigFieldBuilder() {
        if (logCollectorConfigBuilder_ == null) {
          logCollectorConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              LogCollectorConfigOuterClass.LogCollectorConfig, LogCollectorConfigOuterClass.LogCollectorConfig.Builder, LogCollectorConfigOuterClass.LogCollectorConfigOrBuilder>(
                  getLogCollectorConfig(),
                  getParentForChildren(),
                  isClean());
          logCollectorConfig_ = null;
        }
        return logCollectorConfigBuilder_;
      }

      private LoggingConfigOuterClass.SamplingConfig samplingConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          SamplingConfig, SamplingConfig.Builder, SamplingConfigOrBuilder> samplingConfigBuilder_;
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public boolean hasSamplingConfig() {
        return samplingConfigBuilder_ != null || samplingConfig_ != null;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public LoggingConfigOuterClass.SamplingConfig getSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          return samplingConfig_ == null ? LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
        } else {
          return samplingConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(LoggingConfigOuterClass.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          samplingConfig_ = value;
          onChanged();
        } else {
          samplingConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(
          LoggingConfigOuterClass.SamplingConfig.Builder builderForValue) {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = builderForValue.build();
          onChanged();
        } else {
          samplingConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder mergeSamplingConfig(LoggingConfigOuterClass.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (samplingConfig_ != null) {
            samplingConfig_ =
              LoggingConfigOuterClass.SamplingConfig.newBuilder(samplingConfig_).mergeFrom(value).buildPartial();
          } else {
            samplingConfig_ = value;
          }
          onChanged();
        } else {
          samplingConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder clearSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = null;
          onChanged();
        } else {
          samplingConfig_ = null;
          samplingConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public LoggingConfigOuterClass.SamplingConfig.Builder getSamplingConfigBuilder() {

        onChanged();
        return getSamplingConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
        if (samplingConfigBuilder_ != null) {
          return samplingConfigBuilder_.getMessageOrBuilder();
        } else {
          return samplingConfig_ == null ?
              LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
        }
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SamplingConfig, SamplingConfig.Builder, SamplingConfigOrBuilder>
          getSamplingConfigFieldBuilder() {
        if (samplingConfigBuilder_ == null) {
          samplingConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SamplingConfig, SamplingConfig.Builder, SamplingConfigOrBuilder>(
                  getSamplingConfig(),
                  getParentForChildren(),
                  isClean());
          samplingConfig_ = null;
        }
        return samplingConfigBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.LoggingConfig)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.LoggingConfig)
    private static final LoggingConfigOuterClass.LoggingConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoggingConfigOuterClass.LoggingConfig();
    }

    public static LoggingConfigOuterClass.LoggingConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoggingConfig>
        PARSER = new com.google.protobuf.AbstractParser<LoggingConfig>() {
      @Override
      public LoggingConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoggingConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoggingConfig> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoggingConfig> getParserForType() {
      return PARSER;
    }

    @Override
    public LoggingConfigOuterClass.LoggingConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_SamplingConfig_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_SamplingConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_LoggingConfig_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_LoggingConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024logging_config.proto\022\022tensorflow.servi" +
      "ng\032\032log_collector_config.proto\"\'\n\016Sampli" +
      "ngConfig\022\025\n\rsampling_rate\030\001 \001(\001\"\222\001\n\rLogg" +
      "ingConfig\022D\n\024log_collector_config\030\001 \001(\0132" +
      "&.tensorflow.serving.LogCollectorConfig\022" +
      ";\n\017sampling_config\030\002 \001(\0132\".tensorflow.se" +
      "rving.SamplingConfigB\003\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          LogCollectorConfigOuterClass.getDescriptor(),
        });
    internal_static_tensorflow_serving_SamplingConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_SamplingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_SamplingConfig_descriptor,
        new String[] { "SamplingRate", });
    internal_static_tensorflow_serving_LoggingConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_serving_LoggingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_LoggingConfig_descriptor,
        new String[] { "LogCollectorConfig", "SamplingConfig", });
    LogCollectorConfigOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
