// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model_management.proto

package tensorflow.serving;

public final class ModelManagement {
  private ModelManagement() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReloadConfigRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.ReloadConfigRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
     */
    boolean hasConfig();
    /**
     * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
     */
    ModelServerConfigOuterClass.ModelServerConfig getConfig();
    /**
     * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
     */
    ModelServerConfigOuterClass.ModelServerConfigOrBuilder getConfigOrBuilder();
  }
  /**
   * Protobuf type {@code tensorflow.serving.ReloadConfigRequest}
   */
  public  static final class ReloadConfigRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.ReloadConfigRequest)
      ReloadConfigRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReloadConfigRequest.newBuilder() to construct.
    private ReloadConfigRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReloadConfigRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReloadConfigRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReloadConfigRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ModelServerConfigOuterClass.ModelServerConfig.Builder subBuilder = null;
              if (config_ != null) {
                subBuilder = config_.toBuilder();
              }
              config_ = input.readMessage(ModelServerConfigOuterClass.ModelServerConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(config_);
                config_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ModelManagement.internal_static_tensorflow_serving_ReloadConfigRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ModelManagement.internal_static_tensorflow_serving_ReloadConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ModelManagement.ReloadConfigRequest.class, ModelManagement.ReloadConfigRequest.Builder.class);
    }

    public static final int CONFIG_FIELD_NUMBER = 1;
    private ModelServerConfigOuterClass.ModelServerConfig config_;
    /**
     * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
     */
    public boolean hasConfig() {
      return config_ != null;
    }
    /**
     * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
     */
    public ModelServerConfigOuterClass.ModelServerConfig getConfig() {
      return config_ == null ? ModelServerConfigOuterClass.ModelServerConfig.getDefaultInstance() : config_;
    }
    /**
     * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
     */
    public ModelServerConfigOuterClass.ModelServerConfigOrBuilder getConfigOrBuilder() {
      return getConfig();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (config_ != null) {
        output.writeMessage(1, getConfig());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (config_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConfig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ModelManagement.ReloadConfigRequest)) {
        return super.equals(obj);
      }
      ModelManagement.ReloadConfigRequest other = (ModelManagement.ReloadConfigRequest) obj;

      if (hasConfig() != other.hasConfig()) return false;
      if (hasConfig()) {
        if (!getConfig()
            .equals(other.getConfig())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConfig()) {
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ModelManagement.ReloadConfigRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ModelManagement.ReloadConfigRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ModelManagement.ReloadConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ModelManagement.ReloadConfigRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.serving.ReloadConfigRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.ReloadConfigRequest)
        ModelManagement.ReloadConfigRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ModelManagement.internal_static_tensorflow_serving_ReloadConfigRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ModelManagement.internal_static_tensorflow_serving_ReloadConfigRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ModelManagement.ReloadConfigRequest.class, ModelManagement.ReloadConfigRequest.Builder.class);
      }

      // Construct using tensorflow.serving.ModelManagement.ReloadConfigRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (configBuilder_ == null) {
          config_ = null;
        } else {
          config_ = null;
          configBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ModelManagement.internal_static_tensorflow_serving_ReloadConfigRequest_descriptor;
      }

      @Override
      public ModelManagement.ReloadConfigRequest getDefaultInstanceForType() {
        return ModelManagement.ReloadConfigRequest.getDefaultInstance();
      }

      @Override
      public ModelManagement.ReloadConfigRequest build() {
        ModelManagement.ReloadConfigRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ModelManagement.ReloadConfigRequest buildPartial() {
        ModelManagement.ReloadConfigRequest result = new ModelManagement.ReloadConfigRequest(this);
        if (configBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = configBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ModelManagement.ReloadConfigRequest) {
          return mergeFrom((ModelManagement.ReloadConfigRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ModelManagement.ReloadConfigRequest other) {
        if (other == ModelManagement.ReloadConfigRequest.getDefaultInstance()) return this;
        if (other.hasConfig()) {
          mergeConfig(other.getConfig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ModelManagement.ReloadConfigRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ModelManagement.ReloadConfigRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ModelServerConfigOuterClass.ModelServerConfig config_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ModelServerConfigOuterClass.ModelServerConfig, ModelServerConfigOuterClass.ModelServerConfig.Builder, ModelServerConfigOuterClass.ModelServerConfigOrBuilder> configBuilder_;
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      public boolean hasConfig() {
        return configBuilder_ != null || config_ != null;
      }
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      public ModelServerConfigOuterClass.ModelServerConfig getConfig() {
        if (configBuilder_ == null) {
          return config_ == null ? ModelServerConfigOuterClass.ModelServerConfig.getDefaultInstance() : config_;
        } else {
          return configBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      public Builder setConfig(ModelServerConfigOuterClass.ModelServerConfig value) {
        if (configBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          config_ = value;
          onChanged();
        } else {
          configBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      public Builder setConfig(
          ModelServerConfigOuterClass.ModelServerConfig.Builder builderForValue) {
        if (configBuilder_ == null) {
          config_ = builderForValue.build();
          onChanged();
        } else {
          configBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      public Builder mergeConfig(ModelServerConfigOuterClass.ModelServerConfig value) {
        if (configBuilder_ == null) {
          if (config_ != null) {
            config_ =
              ModelServerConfigOuterClass.ModelServerConfig.newBuilder(config_).mergeFrom(value).buildPartial();
          } else {
            config_ = value;
          }
          onChanged();
        } else {
          configBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      public Builder clearConfig() {
        if (configBuilder_ == null) {
          config_ = null;
          onChanged();
        } else {
          config_ = null;
          configBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      public ModelServerConfigOuterClass.ModelServerConfig.Builder getConfigBuilder() {

        onChanged();
        return getConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      public ModelServerConfigOuterClass.ModelServerConfigOrBuilder getConfigOrBuilder() {
        if (configBuilder_ != null) {
          return configBuilder_.getMessageOrBuilder();
        } else {
          return config_ == null ?
              ModelServerConfigOuterClass.ModelServerConfig.getDefaultInstance() : config_;
        }
      }
      /**
       * <code>.tensorflow.serving.ModelServerConfig config = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ModelServerConfigOuterClass.ModelServerConfig, ModelServerConfigOuterClass.ModelServerConfig.Builder, ModelServerConfigOuterClass.ModelServerConfigOrBuilder>
          getConfigFieldBuilder() {
        if (configBuilder_ == null) {
          configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ModelServerConfigOuterClass.ModelServerConfig, ModelServerConfigOuterClass.ModelServerConfig.Builder, ModelServerConfigOuterClass.ModelServerConfigOrBuilder>(
                  getConfig(),
                  getParentForChildren(),
                  isClean());
          config_ = null;
        }
        return configBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.ReloadConfigRequest)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.ReloadConfigRequest)
    private static final ModelManagement.ReloadConfigRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ModelManagement.ReloadConfigRequest();
    }

    public static ModelManagement.ReloadConfigRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReloadConfigRequest>
        PARSER = new com.google.protobuf.AbstractParser<ReloadConfigRequest>() {
      @Override
      public ReloadConfigRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReloadConfigRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReloadConfigRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReloadConfigRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public ModelManagement.ReloadConfigRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReloadConfigResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.ReloadConfigResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tensorflow.serving.StatusProto status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>.tensorflow.serving.StatusProto status = 1;</code>
     */
    Status.StatusProto getStatus();
    /**
     * <code>.tensorflow.serving.StatusProto status = 1;</code>
     */
    Status.StatusProtoOrBuilder getStatusOrBuilder();
  }
  /**
   * Protobuf type {@code tensorflow.serving.ReloadConfigResponse}
   */
  public  static final class ReloadConfigResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.ReloadConfigResponse)
      ReloadConfigResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReloadConfigResponse.newBuilder() to construct.
    private ReloadConfigResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReloadConfigResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReloadConfigResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReloadConfigResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Status.StatusProto.Builder subBuilder = null;
              if (status_ != null) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(Status.StatusProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ModelManagement.internal_static_tensorflow_serving_ReloadConfigResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ModelManagement.internal_static_tensorflow_serving_ReloadConfigResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ModelManagement.ReloadConfigResponse.class, ModelManagement.ReloadConfigResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private Status.StatusProto status_;
    /**
     * <code>.tensorflow.serving.StatusProto status = 1;</code>
     */
    public boolean hasStatus() {
      return status_ != null;
    }
    /**
     * <code>.tensorflow.serving.StatusProto status = 1;</code>
     */
    public Status.StatusProto getStatus() {
      return status_ == null ? Status.StatusProto.getDefaultInstance() : status_;
    }
    /**
     * <code>.tensorflow.serving.StatusProto status = 1;</code>
     */
    public Status.StatusProtoOrBuilder getStatusOrBuilder() {
      return getStatus();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != null) {
        output.writeMessage(1, getStatus());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStatus());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ModelManagement.ReloadConfigResponse)) {
        return super.equals(obj);
      }
      ModelManagement.ReloadConfigResponse other = (ModelManagement.ReloadConfigResponse) obj;

      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (!getStatus()
            .equals(other.getStatus())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ModelManagement.ReloadConfigResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ModelManagement.ReloadConfigResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ModelManagement.ReloadConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ModelManagement.ReloadConfigResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.serving.ReloadConfigResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.ReloadConfigResponse)
        ModelManagement.ReloadConfigResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ModelManagement.internal_static_tensorflow_serving_ReloadConfigResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ModelManagement.internal_static_tensorflow_serving_ReloadConfigResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ModelManagement.ReloadConfigResponse.class, ModelManagement.ReloadConfigResponse.Builder.class);
      }

      // Construct using tensorflow.serving.ModelManagement.ReloadConfigResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (statusBuilder_ == null) {
          status_ = null;
        } else {
          status_ = null;
          statusBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ModelManagement.internal_static_tensorflow_serving_ReloadConfigResponse_descriptor;
      }

      @Override
      public ModelManagement.ReloadConfigResponse getDefaultInstanceForType() {
        return ModelManagement.ReloadConfigResponse.getDefaultInstance();
      }

      @Override
      public ModelManagement.ReloadConfigResponse build() {
        ModelManagement.ReloadConfigResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ModelManagement.ReloadConfigResponse buildPartial() {
        ModelManagement.ReloadConfigResponse result = new ModelManagement.ReloadConfigResponse(this);
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ModelManagement.ReloadConfigResponse) {
          return mergeFrom((ModelManagement.ReloadConfigResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ModelManagement.ReloadConfigResponse other) {
        if (other == ModelManagement.ReloadConfigResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ModelManagement.ReloadConfigResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ModelManagement.ReloadConfigResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Status.StatusProto status_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Status.StatusProto, Status.StatusProto.Builder, Status.StatusProtoOrBuilder> statusBuilder_;
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      public boolean hasStatus() {
        return statusBuilder_ != null || status_ != null;
      }
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      public Status.StatusProto getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? Status.StatusProto.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      public Builder setStatus(Status.StatusProto value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      public Builder setStatus(
          Status.StatusProto.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      public Builder mergeStatus(Status.StatusProto value) {
        if (statusBuilder_ == null) {
          if (status_ != null) {
            status_ =
              Status.StatusProto.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = null;
          onChanged();
        } else {
          status_ = null;
          statusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      public Status.StatusProto.Builder getStatusBuilder() {

        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      public Status.StatusProtoOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              Status.StatusProto.getDefaultInstance() : status_;
        }
      }
      /**
       * <code>.tensorflow.serving.StatusProto status = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Status.StatusProto, Status.StatusProto.Builder, Status.StatusProtoOrBuilder>
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Status.StatusProto, Status.StatusProto.Builder, Status.StatusProtoOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.ReloadConfigResponse)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.ReloadConfigResponse)
    private static final ModelManagement.ReloadConfigResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ModelManagement.ReloadConfigResponse();
    }

    public static ModelManagement.ReloadConfigResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReloadConfigResponse>
        PARSER = new com.google.protobuf.AbstractParser<ReloadConfigResponse>() {
      @Override
      public ReloadConfigResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReloadConfigResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReloadConfigResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReloadConfigResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public ModelManagement.ReloadConfigResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_ReloadConfigRequest_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_ReloadConfigRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_ReloadConfigResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_ReloadConfigResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026model_management.proto\022\022tensorflow.ser" +
      "ving\032\031model_server_config.proto\032\014status." +
      "proto\"L\n\023ReloadConfigRequest\0225\n\006config\030\001" +
      " \001(\0132%.tensorflow.serving.ModelServerCon" +
      "fig\"G\n\024ReloadConfigResponse\022/\n\006status\030\001 " +
      "\001(\0132\037.tensorflow.serving.StatusProtoB\003\370\001" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ModelServerConfigOuterClass.getDescriptor(),
          Status.getDescriptor(),
        });
    internal_static_tensorflow_serving_ReloadConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_ReloadConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_ReloadConfigRequest_descriptor,
        new String[] { "Config", });
    internal_static_tensorflow_serving_ReloadConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_serving_ReloadConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_ReloadConfigResponse_descriptor,
        new String[] { "Status", });
    ModelServerConfigOuterClass.getDescriptor();
    Status.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
