// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: predict.proto

package tensorflow.serving;

public final class Predict {
  private Predict() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PredictRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.PredictRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Model Specification. If version is not specified, will use the latest
     * (numerical) version.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    boolean hasModelSpec();
    /**
     * <pre>
     * Model Specification. If version is not specified, will use the latest
     * (numerical) version.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    Model.ModelSpec getModelSpec();
    /**
     * <pre>
     * Model Specification. If version is not specified, will use the latest
     * (numerical) version.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    Model.ModelSpecOrBuilder getModelSpecOrBuilder();

    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */
    int getInputsCount();
    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */
    boolean containsInputs(
            String key);
    /**
     * Use {@link #getInputsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, org.tensorflow.framework.TensorProto>
    getInputs();
    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */
    java.util.Map<String, org.tensorflow.framework.TensorProto>
    getInputsMap();
    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */

    org.tensorflow.framework.TensorProto getInputsOrDefault(
            String key,
            org.tensorflow.framework.TensorProto defaultValue);
    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */

    org.tensorflow.framework.TensorProto getInputsOrThrow(
            String key);

    /**
     * <pre>
     * Output filter.
     * Names specified are alias names. The mapping from aliases to real output
     * tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'outputs' field.
     * Only tensors specified here will be run/fetched and returned, with the
     * exception that when none is specified, all tensors specified in the
     * named signature will be run/fetched and returned.
     * </pre>
     *
     * <code>repeated string output_filter = 3;</code>
     */
    java.util.List<String>
        getOutputFilterList();
    /**
     * <pre>
     * Output filter.
     * Names specified are alias names. The mapping from aliases to real output
     * tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'outputs' field.
     * Only tensors specified here will be run/fetched and returned, with the
     * exception that when none is specified, all tensors specified in the
     * named signature will be run/fetched and returned.
     * </pre>
     *
     * <code>repeated string output_filter = 3;</code>
     */
    int getOutputFilterCount();
    /**
     * <pre>
     * Output filter.
     * Names specified are alias names. The mapping from aliases to real output
     * tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'outputs' field.
     * Only tensors specified here will be run/fetched and returned, with the
     * exception that when none is specified, all tensors specified in the
     * named signature will be run/fetched and returned.
     * </pre>
     *
     * <code>repeated string output_filter = 3;</code>
     */
    String getOutputFilter(int index);
    /**
     * <pre>
     * Output filter.
     * Names specified are alias names. The mapping from aliases to real output
     * tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'outputs' field.
     * Only tensors specified here will be run/fetched and returned, with the
     * exception that when none is specified, all tensors specified in the
     * named signature will be run/fetched and returned.
     * </pre>
     *
     * <code>repeated string output_filter = 3;</code>
     */
    com.google.protobuf.ByteString
        getOutputFilterBytes(int index);
  }
  /**
   * <pre>
   * PredictRequest specifies which TensorFlow model to run, as well as
   * how inputs are mapped to tensors and how outputs are filtered before
   * returning to user.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.PredictRequest}
   */
  public  static final class PredictRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.PredictRequest)
      PredictRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PredictRequest.newBuilder() to construct.
    private PredictRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PredictRequest() {
      outputFilter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PredictRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PredictRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Model.ModelSpec.Builder subBuilder = null;
              if (modelSpec_ != null) {
                subBuilder = modelSpec_.toBuilder();
              }
              modelSpec_ = input.readMessage(Model.ModelSpec.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(modelSpec_);
                modelSpec_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                inputs_ = com.google.protobuf.MapField.newMapField(
                    InputsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, org.tensorflow.framework.TensorProto>
              inputs__ = input.readMessage(
                  InputsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              inputs_.getMutableMap().put(
                  inputs__.getKey(), inputs__.getValue());
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                outputFilter_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              outputFilter_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          outputFilter_ = outputFilter_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Predict.internal_static_tensorflow_serving_PredictRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetInputs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Predict.internal_static_tensorflow_serving_PredictRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Predict.PredictRequest.class, Predict.PredictRequest.Builder.class);
    }

    public static final int MODEL_SPEC_FIELD_NUMBER = 1;
    private Model.ModelSpec modelSpec_;
    /**
     * <pre>
     * Model Specification. If version is not specified, will use the latest
     * (numerical) version.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    public boolean hasModelSpec() {
      return modelSpec_ != null;
    }
    /**
     * <pre>
     * Model Specification. If version is not specified, will use the latest
     * (numerical) version.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    public Model.ModelSpec getModelSpec() {
      return modelSpec_ == null ? Model.ModelSpec.getDefaultInstance() : modelSpec_;
    }
    /**
     * <pre>
     * Model Specification. If version is not specified, will use the latest
     * (numerical) version.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    public Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
      return getModelSpec();
    }

    public static final int INPUTS_FIELD_NUMBER = 2;
    private static final class InputsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, org.tensorflow.framework.TensorProto> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, org.tensorflow.framework.TensorProto>newDefaultInstance(
                  Predict.internal_static_tensorflow_serving_PredictRequest_InputsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  org.tensorflow.framework.TensorProto.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, org.tensorflow.framework.TensorProto> inputs_;
    private com.google.protobuf.MapField<String, org.tensorflow.framework.TensorProto>
    internalGetInputs() {
      if (inputs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InputsDefaultEntryHolder.defaultEntry);
      }
      return inputs_;
    }

    public int getInputsCount() {
      return internalGetInputs().getMap().size();
    }
    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */

    public boolean containsInputs(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetInputs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInputsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, org.tensorflow.framework.TensorProto> getInputs() {
      return getInputsMap();
    }
    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */

    public java.util.Map<String, org.tensorflow.framework.TensorProto> getInputsMap() {
      return internalGetInputs().getMap();
    }
    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */

    public org.tensorflow.framework.TensorProto getInputsOrDefault(
        String key,
        org.tensorflow.framework.TensorProto defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, org.tensorflow.framework.TensorProto> map =
          internalGetInputs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Input tensors.
     * Names of input tensor are alias names. The mapping from aliases to real
     * input tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'inputs' field.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
     */

    public org.tensorflow.framework.TensorProto getInputsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, org.tensorflow.framework.TensorProto> map =
          internalGetInputs().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int OUTPUT_FILTER_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList outputFilter_;
    /**
     * <pre>
     * Output filter.
     * Names specified are alias names. The mapping from aliases to real output
     * tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'outputs' field.
     * Only tensors specified here will be run/fetched and returned, with the
     * exception that when none is specified, all tensors specified in the
     * named signature will be run/fetched and returned.
     * </pre>
     *
     * <code>repeated string output_filter = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOutputFilterList() {
      return outputFilter_;
    }
    /**
     * <pre>
     * Output filter.
     * Names specified are alias names. The mapping from aliases to real output
     * tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'outputs' field.
     * Only tensors specified here will be run/fetched and returned, with the
     * exception that when none is specified, all tensors specified in the
     * named signature will be run/fetched and returned.
     * </pre>
     *
     * <code>repeated string output_filter = 3;</code>
     */
    public int getOutputFilterCount() {
      return outputFilter_.size();
    }
    /**
     * <pre>
     * Output filter.
     * Names specified are alias names. The mapping from aliases to real output
     * tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'outputs' field.
     * Only tensors specified here will be run/fetched and returned, with the
     * exception that when none is specified, all tensors specified in the
     * named signature will be run/fetched and returned.
     * </pre>
     *
     * <code>repeated string output_filter = 3;</code>
     */
    public String getOutputFilter(int index) {
      return outputFilter_.get(index);
    }
    /**
     * <pre>
     * Output filter.
     * Names specified are alias names. The mapping from aliases to real output
     * tensor names is stored in the SavedModel export as a prediction
     * SignatureDef under the 'outputs' field.
     * Only tensors specified here will be run/fetched and returned, with the
     * exception that when none is specified, all tensors specified in the
     * named signature will be run/fetched and returned.
     * </pre>
     *
     * <code>repeated string output_filter = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOutputFilterBytes(int index) {
      return outputFilter_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (modelSpec_ != null) {
        output.writeMessage(1, getModelSpec());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetInputs(),
          InputsDefaultEntryHolder.defaultEntry,
          2);
      for (int i = 0; i < outputFilter_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, outputFilter_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (modelSpec_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getModelSpec());
      }
      for (java.util.Map.Entry<String, org.tensorflow.framework.TensorProto> entry
           : internalGetInputs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, org.tensorflow.framework.TensorProto>
        inputs__ = InputsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, inputs__);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < outputFilter_.size(); i++) {
          dataSize += computeStringSizeNoTag(outputFilter_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOutputFilterList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Predict.PredictRequest)) {
        return super.equals(obj);
      }
      Predict.PredictRequest other = (Predict.PredictRequest) obj;

      if (hasModelSpec() != other.hasModelSpec()) return false;
      if (hasModelSpec()) {
        if (!getModelSpec()
            .equals(other.getModelSpec())) return false;
      }
      if (!internalGetInputs().equals(
          other.internalGetInputs())) return false;
      if (!getOutputFilterList()
          .equals(other.getOutputFilterList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModelSpec()) {
        hash = (37 * hash) + MODEL_SPEC_FIELD_NUMBER;
        hash = (53 * hash) + getModelSpec().hashCode();
      }
      if (!internalGetInputs().getMap().isEmpty()) {
        hash = (37 * hash) + INPUTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetInputs().hashCode();
      }
      if (getOutputFilterCount() > 0) {
        hash = (37 * hash) + OUTPUT_FILTER_FIELD_NUMBER;
        hash = (53 * hash) + getOutputFilterList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Predict.PredictRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Predict.PredictRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Predict.PredictRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Predict.PredictRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Predict.PredictRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Predict.PredictRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Predict.PredictRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Predict.PredictRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Predict.PredictRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Predict.PredictRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Predict.PredictRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Predict.PredictRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Predict.PredictRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * PredictRequest specifies which TensorFlow model to run, as well as
     * how inputs are mapped to tensors and how outputs are filtered before
     * returning to user.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.PredictRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.PredictRequest)
        Predict.PredictRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Predict.internal_static_tensorflow_serving_PredictRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetInputs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableInputs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Predict.internal_static_tensorflow_serving_PredictRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Predict.PredictRequest.class, Predict.PredictRequest.Builder.class);
      }

      // Construct using tensorflow.serving.Predict.PredictRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }
        internalGetMutableInputs().clear();
        outputFilter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Predict.internal_static_tensorflow_serving_PredictRequest_descriptor;
      }

      @Override
      public Predict.PredictRequest getDefaultInstanceForType() {
        return Predict.PredictRequest.getDefaultInstance();
      }

      @Override
      public Predict.PredictRequest build() {
        Predict.PredictRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Predict.PredictRequest buildPartial() {
        Predict.PredictRequest result = new Predict.PredictRequest(this);
        int from_bitField0_ = bitField0_;
        if (modelSpecBuilder_ == null) {
          result.modelSpec_ = modelSpec_;
        } else {
          result.modelSpec_ = modelSpecBuilder_.build();
        }
        result.inputs_ = internalGetInputs();
        result.inputs_.makeImmutable();
        if (((bitField0_ & 0x00000002) != 0)) {
          outputFilter_ = outputFilter_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.outputFilter_ = outputFilter_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Predict.PredictRequest) {
          return mergeFrom((Predict.PredictRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Predict.PredictRequest other) {
        if (other == Predict.PredictRequest.getDefaultInstance()) return this;
        if (other.hasModelSpec()) {
          mergeModelSpec(other.getModelSpec());
        }
        internalGetMutableInputs().mergeFrom(
            other.internalGetInputs());
        if (!other.outputFilter_.isEmpty()) {
          if (outputFilter_.isEmpty()) {
            outputFilter_ = other.outputFilter_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOutputFilterIsMutable();
            outputFilter_.addAll(other.outputFilter_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Predict.PredictRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Predict.PredictRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Model.ModelSpec modelSpec_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder> modelSpecBuilder_;
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public boolean hasModelSpec() {
        return modelSpecBuilder_ != null || modelSpec_ != null;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Model.ModelSpec getModelSpec() {
        if (modelSpecBuilder_ == null) {
          return modelSpec_ == null ? Model.ModelSpec.getDefaultInstance() : modelSpec_;
        } else {
          return modelSpecBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modelSpec_ = value;
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(
          Model.ModelSpec.Builder builderForValue) {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = builderForValue.build();
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder mergeModelSpec(Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (modelSpec_ != null) {
            modelSpec_ =
              Model.ModelSpec.newBuilder(modelSpec_).mergeFrom(value).buildPartial();
          } else {
            modelSpec_ = value;
          }
          onChanged();
        } else {
          modelSpecBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder clearModelSpec() {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
          onChanged();
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Model.ModelSpec.Builder getModelSpecBuilder() {

        onChanged();
        return getModelSpecFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
        if (modelSpecBuilder_ != null) {
          return modelSpecBuilder_.getMessageOrBuilder();
        } else {
          return modelSpec_ == null ?
              Model.ModelSpec.getDefaultInstance() : modelSpec_;
        }
      }
      /**
       * <pre>
       * Model Specification. If version is not specified, will use the latest
       * (numerical) version.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder>
          getModelSpecFieldBuilder() {
        if (modelSpecBuilder_ == null) {
          modelSpecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder>(
                  getModelSpec(),
                  getParentForChildren(),
                  isClean());
          modelSpec_ = null;
        }
        return modelSpecBuilder_;
      }

      private com.google.protobuf.MapField<
          String, org.tensorflow.framework.TensorProto> inputs_;
      private com.google.protobuf.MapField<String, org.tensorflow.framework.TensorProto>
      internalGetInputs() {
        if (inputs_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              InputsDefaultEntryHolder.defaultEntry);
        }
        return inputs_;
      }
      private com.google.protobuf.MapField<String, org.tensorflow.framework.TensorProto>
      internalGetMutableInputs() {
        onChanged();;
        if (inputs_ == null) {
          inputs_ = com.google.protobuf.MapField.newMapField(
              InputsDefaultEntryHolder.defaultEntry);
        }
        if (!inputs_.isMutable()) {
          inputs_ = inputs_.copy();
        }
        return inputs_;
      }

      public int getInputsCount() {
        return internalGetInputs().getMap().size();
      }
      /**
       * <pre>
       * Input tensors.
       * Names of input tensor are alias names. The mapping from aliases to real
       * input tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'inputs' field.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
       */

      public boolean containsInputs(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetInputs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getInputsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, org.tensorflow.framework.TensorProto> getInputs() {
        return getInputsMap();
      }
      /**
       * <pre>
       * Input tensors.
       * Names of input tensor are alias names. The mapping from aliases to real
       * input tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'inputs' field.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
       */

      public java.util.Map<String, org.tensorflow.framework.TensorProto> getInputsMap() {
        return internalGetInputs().getMap();
      }
      /**
       * <pre>
       * Input tensors.
       * Names of input tensor are alias names. The mapping from aliases to real
       * input tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'inputs' field.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
       */

      public org.tensorflow.framework.TensorProto getInputsOrDefault(
          String key,
          org.tensorflow.framework.TensorProto defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, org.tensorflow.framework.TensorProto> map =
            internalGetInputs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Input tensors.
       * Names of input tensor are alias names. The mapping from aliases to real
       * input tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'inputs' field.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
       */

      public org.tensorflow.framework.TensorProto getInputsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, org.tensorflow.framework.TensorProto> map =
            internalGetInputs().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearInputs() {
        internalGetMutableInputs().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Input tensors.
       * Names of input tensor are alias names. The mapping from aliases to real
       * input tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'inputs' field.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
       */

      public Builder removeInputs(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableInputs().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, org.tensorflow.framework.TensorProto>
      getMutableInputs() {
        return internalGetMutableInputs().getMutableMap();
      }
      /**
       * <pre>
       * Input tensors.
       * Names of input tensor are alias names. The mapping from aliases to real
       * input tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'inputs' field.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
       */
      public Builder putInputs(
          String key,
          org.tensorflow.framework.TensorProto value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableInputs().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Input tensors.
       * Names of input tensor are alias names. The mapping from aliases to real
       * input tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'inputs' field.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; inputs = 2;</code>
       */

      public Builder putAllInputs(
          java.util.Map<String, org.tensorflow.framework.TensorProto> values) {
        internalGetMutableInputs().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.LazyStringList outputFilter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOutputFilterIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          outputFilter_ = new com.google.protobuf.LazyStringArrayList(outputFilter_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getOutputFilterList() {
        return outputFilter_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public int getOutputFilterCount() {
        return outputFilter_.size();
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public String getOutputFilter(int index) {
        return outputFilter_.get(index);
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOutputFilterBytes(int index) {
        return outputFilter_.getByteString(index);
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public Builder setOutputFilter(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputFilterIsMutable();
        outputFilter_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public Builder addOutputFilter(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputFilterIsMutable();
        outputFilter_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public Builder addAllOutputFilter(
          Iterable<String> values) {
        ensureOutputFilterIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, outputFilter_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public Builder clearOutputFilter() {
        outputFilter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Output filter.
       * Names specified are alias names. The mapping from aliases to real output
       * tensor names is stored in the SavedModel export as a prediction
       * SignatureDef under the 'outputs' field.
       * Only tensors specified here will be run/fetched and returned, with the
       * exception that when none is specified, all tensors specified in the
       * named signature will be run/fetched and returned.
       * </pre>
       *
       * <code>repeated string output_filter = 3;</code>
       */
      public Builder addOutputFilterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureOutputFilterIsMutable();
        outputFilter_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.PredictRequest)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.PredictRequest)
    private static final Predict.PredictRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Predict.PredictRequest();
    }

    public static Predict.PredictRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PredictRequest>
        PARSER = new com.google.protobuf.AbstractParser<PredictRequest>() {
      @Override
      public PredictRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PredictRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PredictRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PredictRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public Predict.PredictRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PredictResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.PredictResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Effective Model Specification used to process PredictRequest.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
     */
    boolean hasModelSpec();
    /**
     * <pre>
     * Effective Model Specification used to process PredictRequest.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
     */
    Model.ModelSpec getModelSpec();
    /**
     * <pre>
     * Effective Model Specification used to process PredictRequest.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
     */
    Model.ModelSpecOrBuilder getModelSpecOrBuilder();

    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */
    int getOutputsCount();
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */
    boolean containsOutputs(
            String key);
    /**
     * Use {@link #getOutputsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, org.tensorflow.framework.TensorProto>
    getOutputs();
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */
    java.util.Map<String, org.tensorflow.framework.TensorProto>
    getOutputsMap();
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */

    org.tensorflow.framework.TensorProto getOutputsOrDefault(
            String key,
            org.tensorflow.framework.TensorProto defaultValue);
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */

    org.tensorflow.framework.TensorProto getOutputsOrThrow(
            String key);
  }
  /**
   * <pre>
   * Response for PredictRequest on successful run.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.PredictResponse}
   */
  public  static final class PredictResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.PredictResponse)
      PredictResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PredictResponse.newBuilder() to construct.
    private PredictResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PredictResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PredictResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PredictResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                outputs_ = com.google.protobuf.MapField.newMapField(
                    OutputsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, org.tensorflow.framework.TensorProto>
              outputs__ = input.readMessage(
                  OutputsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              outputs_.getMutableMap().put(
                  outputs__.getKey(), outputs__.getValue());
              break;
            }
            case 18: {
              Model.ModelSpec.Builder subBuilder = null;
              if (modelSpec_ != null) {
                subBuilder = modelSpec_.toBuilder();
              }
              modelSpec_ = input.readMessage(Model.ModelSpec.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(modelSpec_);
                modelSpec_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Predict.internal_static_tensorflow_serving_PredictResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetOutputs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Predict.internal_static_tensorflow_serving_PredictResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Predict.PredictResponse.class, Predict.PredictResponse.Builder.class);
    }

    public static final int MODEL_SPEC_FIELD_NUMBER = 2;
    private Model.ModelSpec modelSpec_;
    /**
     * <pre>
     * Effective Model Specification used to process PredictRequest.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
     */
    public boolean hasModelSpec() {
      return modelSpec_ != null;
    }
    /**
     * <pre>
     * Effective Model Specification used to process PredictRequest.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
     */
    public Model.ModelSpec getModelSpec() {
      return modelSpec_ == null ? Model.ModelSpec.getDefaultInstance() : modelSpec_;
    }
    /**
     * <pre>
     * Effective Model Specification used to process PredictRequest.
     * </pre>
     *
     * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
     */
    public Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
      return getModelSpec();
    }

    public static final int OUTPUTS_FIELD_NUMBER = 1;
    private static final class OutputsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, org.tensorflow.framework.TensorProto> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, org.tensorflow.framework.TensorProto>newDefaultInstance(
                  Predict.internal_static_tensorflow_serving_PredictResponse_OutputsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  org.tensorflow.framework.TensorProto.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, org.tensorflow.framework.TensorProto> outputs_;
    private com.google.protobuf.MapField<String, org.tensorflow.framework.TensorProto>
    internalGetOutputs() {
      if (outputs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OutputsDefaultEntryHolder.defaultEntry);
      }
      return outputs_;
    }

    public int getOutputsCount() {
      return internalGetOutputs().getMap().size();
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */

    public boolean containsOutputs(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetOutputs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOutputsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, org.tensorflow.framework.TensorProto> getOutputs() {
      return getOutputsMap();
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */

    public java.util.Map<String, org.tensorflow.framework.TensorProto> getOutputsMap() {
      return internalGetOutputs().getMap();
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */

    public org.tensorflow.framework.TensorProto getOutputsOrDefault(
        String key,
        org.tensorflow.framework.TensorProto defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, org.tensorflow.framework.TensorProto> map =
          internalGetOutputs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
     */

    public org.tensorflow.framework.TensorProto getOutputsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, org.tensorflow.framework.TensorProto> map =
          internalGetOutputs().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetOutputs(),
          OutputsDefaultEntryHolder.defaultEntry,
          1);
      if (modelSpec_ != null) {
        output.writeMessage(2, getModelSpec());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<String, org.tensorflow.framework.TensorProto> entry
           : internalGetOutputs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, org.tensorflow.framework.TensorProto>
        outputs__ = OutputsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, outputs__);
      }
      if (modelSpec_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getModelSpec());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Predict.PredictResponse)) {
        return super.equals(obj);
      }
      Predict.PredictResponse other = (Predict.PredictResponse) obj;

      if (hasModelSpec() != other.hasModelSpec()) return false;
      if (hasModelSpec()) {
        if (!getModelSpec()
            .equals(other.getModelSpec())) return false;
      }
      if (!internalGetOutputs().equals(
          other.internalGetOutputs())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModelSpec()) {
        hash = (37 * hash) + MODEL_SPEC_FIELD_NUMBER;
        hash = (53 * hash) + getModelSpec().hashCode();
      }
      if (!internalGetOutputs().getMap().isEmpty()) {
        hash = (37 * hash) + OUTPUTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOutputs().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Predict.PredictResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Predict.PredictResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Predict.PredictResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Predict.PredictResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Predict.PredictResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Predict.PredictResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Predict.PredictResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Predict.PredictResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Predict.PredictResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Predict.PredictResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Predict.PredictResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Predict.PredictResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Predict.PredictResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response for PredictRequest on successful run.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.PredictResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.PredictResponse)
        Predict.PredictResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Predict.internal_static_tensorflow_serving_PredictResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetOutputs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableOutputs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Predict.internal_static_tensorflow_serving_PredictResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Predict.PredictResponse.class, Predict.PredictResponse.Builder.class);
      }

      // Construct using tensorflow.serving.Predict.PredictResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }
        internalGetMutableOutputs().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Predict.internal_static_tensorflow_serving_PredictResponse_descriptor;
      }

      @Override
      public Predict.PredictResponse getDefaultInstanceForType() {
        return Predict.PredictResponse.getDefaultInstance();
      }

      @Override
      public Predict.PredictResponse build() {
        Predict.PredictResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Predict.PredictResponse buildPartial() {
        Predict.PredictResponse result = new Predict.PredictResponse(this);
        int from_bitField0_ = bitField0_;
        if (modelSpecBuilder_ == null) {
          result.modelSpec_ = modelSpec_;
        } else {
          result.modelSpec_ = modelSpecBuilder_.build();
        }
        result.outputs_ = internalGetOutputs();
        result.outputs_.makeImmutable();
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Predict.PredictResponse) {
          return mergeFrom((Predict.PredictResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Predict.PredictResponse other) {
        if (other == Predict.PredictResponse.getDefaultInstance()) return this;
        if (other.hasModelSpec()) {
          mergeModelSpec(other.getModelSpec());
        }
        internalGetMutableOutputs().mergeFrom(
            other.internalGetOutputs());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Predict.PredictResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Predict.PredictResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Model.ModelSpec modelSpec_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder> modelSpecBuilder_;
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      public boolean hasModelSpec() {
        return modelSpecBuilder_ != null || modelSpec_ != null;
      }
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      public Model.ModelSpec getModelSpec() {
        if (modelSpecBuilder_ == null) {
          return modelSpec_ == null ? Model.ModelSpec.getDefaultInstance() : modelSpec_;
        } else {
          return modelSpecBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      public Builder setModelSpec(Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modelSpec_ = value;
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      public Builder setModelSpec(
          Model.ModelSpec.Builder builderForValue) {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = builderForValue.build();
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      public Builder mergeModelSpec(Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (modelSpec_ != null) {
            modelSpec_ =
              Model.ModelSpec.newBuilder(modelSpec_).mergeFrom(value).buildPartial();
          } else {
            modelSpec_ = value;
          }
          onChanged();
        } else {
          modelSpecBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      public Builder clearModelSpec() {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
          onChanged();
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      public Model.ModelSpec.Builder getModelSpecBuilder() {

        onChanged();
        return getModelSpecFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      public Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
        if (modelSpecBuilder_ != null) {
          return modelSpecBuilder_.getMessageOrBuilder();
        } else {
          return modelSpec_ == null ?
              Model.ModelSpec.getDefaultInstance() : modelSpec_;
        }
      }
      /**
       * <pre>
       * Effective Model Specification used to process PredictRequest.
       * </pre>
       *
       * <code>.tensorflow.serving.ModelSpec model_spec = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder>
          getModelSpecFieldBuilder() {
        if (modelSpecBuilder_ == null) {
          modelSpecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Model.ModelSpec, Model.ModelSpec.Builder, Model.ModelSpecOrBuilder>(
                  getModelSpec(),
                  getParentForChildren(),
                  isClean());
          modelSpec_ = null;
        }
        return modelSpecBuilder_;
      }

      private com.google.protobuf.MapField<
          String, org.tensorflow.framework.TensorProto> outputs_;
      private com.google.protobuf.MapField<String, org.tensorflow.framework.TensorProto>
      internalGetOutputs() {
        if (outputs_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OutputsDefaultEntryHolder.defaultEntry);
        }
        return outputs_;
      }
      private com.google.protobuf.MapField<String, org.tensorflow.framework.TensorProto>
      internalGetMutableOutputs() {
        onChanged();;
        if (outputs_ == null) {
          outputs_ = com.google.protobuf.MapField.newMapField(
              OutputsDefaultEntryHolder.defaultEntry);
        }
        if (!outputs_.isMutable()) {
          outputs_ = outputs_.copy();
        }
        return outputs_;
      }

      public int getOutputsCount() {
        return internalGetOutputs().getMap().size();
      }
      /**
       * <pre>
       * Output tensors.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
       */

      public boolean containsOutputs(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetOutputs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOutputsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, org.tensorflow.framework.TensorProto> getOutputs() {
        return getOutputsMap();
      }
      /**
       * <pre>
       * Output tensors.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
       */

      public java.util.Map<String, org.tensorflow.framework.TensorProto> getOutputsMap() {
        return internalGetOutputs().getMap();
      }
      /**
       * <pre>
       * Output tensors.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
       */

      public org.tensorflow.framework.TensorProto getOutputsOrDefault(
          String key,
          org.tensorflow.framework.TensorProto defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, org.tensorflow.framework.TensorProto> map =
            internalGetOutputs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Output tensors.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
       */

      public org.tensorflow.framework.TensorProto getOutputsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, org.tensorflow.framework.TensorProto> map =
            internalGetOutputs().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearOutputs() {
        internalGetMutableOutputs().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Output tensors.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
       */

      public Builder removeOutputs(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableOutputs().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, org.tensorflow.framework.TensorProto>
      getMutableOutputs() {
        return internalGetMutableOutputs().getMutableMap();
      }
      /**
       * <pre>
       * Output tensors.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
       */
      public Builder putOutputs(
          String key,
          org.tensorflow.framework.TensorProto value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableOutputs().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Output tensors.
       * </pre>
       *
       * <code>map&lt;string, .tensorflow.TensorProto&gt; outputs = 1;</code>
       */

      public Builder putAllOutputs(
          java.util.Map<String, org.tensorflow.framework.TensorProto> values) {
        internalGetMutableOutputs().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.PredictResponse)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.PredictResponse)
    private static final Predict.PredictResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Predict.PredictResponse();
    }

    public static Predict.PredictResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PredictResponse>
        PARSER = new com.google.protobuf.AbstractParser<PredictResponse>() {
      @Override
      public PredictResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PredictResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PredictResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PredictResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public Predict.PredictResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_PredictRequest_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_PredictRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_PredictRequest_InputsEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_PredictRequest_InputsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_PredictResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_PredictResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_PredictResponse_OutputsEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_PredictResponse_OutputsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rpredict.proto\022\022tensorflow.serving\032\014ten" +
      "sor.proto\032\013model.proto\"\342\001\n\016PredictReques" +
      "t\0221\n\nmodel_spec\030\001 \001(\0132\035.tensorflow.servi" +
      "ng.ModelSpec\022>\n\006inputs\030\002 \003(\0132..tensorflo" +
      "w.serving.PredictRequest.InputsEntry\022\025\n\r" +
      "output_filter\030\003 \003(\t\032F\n\013InputsEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022&\n\005value\030\002 \001(\0132\027.tensorflow.Tens" +
      "orProto:\0028\001\"\320\001\n\017PredictResponse\0221\n\nmodel" +
      "_spec\030\002 \001(\0132\035.tensorflow.serving.ModelSp" +
      "ec\022A\n\007outputs\030\001 \003(\01320.tensorflow.serving" +
      ".PredictResponse.OutputsEntry\032G\n\014Outputs" +
      "Entry\022\013\n\003key\030\001 \001(\t\022&\n\005value\030\002 \001(\0132\027.tens" +
      "orflow.TensorProto:\0028\001B\003\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.TensorProtos.getDescriptor(),
          Model.getDescriptor(),
        });
    internal_static_tensorflow_serving_PredictRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_PredictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_PredictRequest_descriptor,
        new String[] { "ModelSpec", "Inputs", "OutputFilter", });
    internal_static_tensorflow_serving_PredictRequest_InputsEntry_descriptor =
      internal_static_tensorflow_serving_PredictRequest_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_serving_PredictRequest_InputsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_PredictRequest_InputsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_tensorflow_serving_PredictResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_serving_PredictResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_PredictResponse_descriptor,
        new String[] { "ModelSpec", "Outputs", });
    internal_static_tensorflow_serving_PredictResponse_OutputsEntry_descriptor =
      internal_static_tensorflow_serving_PredictResponse_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_serving_PredictResponse_OutputsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_PredictResponse_OutputsEntry_descriptor,
        new String[] { "Key", "Value", });
    org.tensorflow.framework.TensorProtos.getDescriptor();
    Model.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
